### PR TITLE
feat(print): add message when there's nothing to print

### LINKED ISSUE #3: Add a message when there's nothing to show
Currently nothing is printed when no relevant data is returned, e.g nothing changed during the time range (`--since` flag). 

A friendlier approach would be to print a message to the user, this giving feedback that this isn't an error but there's no data to show

### PR DESCRIPTION
**Pull request by hagaibarel**
Add a print message when the release data size returned is 0.

Also, clean up the print function a bit

Closes #3 

Signed-off-by: Hagai Barel <hagaibarel@gmail.com>

### CODE REVIEW

**Comment by maorfr** [comment]
this approach is consistent with other helm commands, such as `helm ls`.
do you think it is required despite that?

**Comment by hagaibarel** [comment]
Perhaps, yet it's common in other cli tools (e.g. kubectl, terraform) to
print out messages such as this to let you know that there wasn't an error,
just nothing to show

**Comment by maorfr** [comment]
I think it is better to be consistent with the tool we plug in to, rather then other tools.

Can we use `--debug` for this?

**Comment by hagaibarel** [comment]
Sorry for the late response, busy couple of days.

I agree with you on consistency, although I have my reservations about helm's UX. We can maybe place it under a `--debug` flag, but I think that will force us to change the logging mechanism, the current `log` implementation from the `stdlib` doesn't support leveled logging. I'd love to talk on it in a different issue if you'd like, it feels out of scope for this PR.

Moving forward, would like me to remove the offending [line](https://github.com/maorfr/helm-logs/pull/4/files#diff-7ddfb3e035b42cd70649cc33393fe32cR235), or close the PR all together?

**Comment by maorfr** [comment]
i'll go with you on this one.

**Pull request merged**
